### ISSUE TITLE
Is Library Ready for Use?

### ISSUE THREAD

**Issue by Shabinder** [alialbaali/Kamel#1]
Hey, Library Looks Good , is it ready for loading Images Over Net in a KMP project consisting of Desktop , Android Platforms.

**Comment by Shabinder** [comment]
I tried Adding the Dependency , but it wasnt coming up in my source files...? Any guess what could be the issue?

**Comment by alialbaali** [comment]
Yeah I'll probably publish it fully in a couple of days and announce it on Slack. Just gotta add few things before that.

**Comment by alialbaali** [comment]
There's also snapshot version 0.0.7-SNAPSHOT, to get that you need to add snapshots repository which is `maven(url = "https://oss.sonatype.org/content/repositories/snapshots/")`

**Comment by alialbaali** [comment]
You can try it now. version 0.0.7 is published.
