### ISSUE TITLE
Class 'io.kamel.core.Resource' is compiled by an unstable version of the Kotlin compiler and cannot be loaded by this compiler

### ISSUE THREAD

**Issue by Shabinder** [alialbaali/Kamel#2]
Lib needs updation to Kotlin 1.4.30 for following error to fix:
Class 'io.kamel.core.Resource' is compiled by an unstable version of the Kotlin compiler and cannot be loaded by this compiler

**Comment by alialbaali** [comment]
If you're using version 0.1.0 then Kamel Kotlin version is 1.4.30 and compose is 0.3.0-build152.

What versions are you using and does your project compile?

**Comment by Shabinder** [comment]
> If you're using version 0.1.0 then Kamel's Kotlin version is 1.4.30 and compose version is 0.3.0-build152.
> 
> What versions are you using and does your project compile?

yup without Kamel , project compiles just fine.
using 0.0.7 Kamel's version.

**Comment by alialbaali** [comment]
Version 0.0.7 is based on Kotlin 1.4.21-2 and compose build 148. That's why it doesn't compile.
