### ISSUE TITLE
Failed to resolve Desktop Compose on Android

### ISSUE THREAD

**Issue by jakepurple13** [alialbaali/Kamel#24]
I'm trying to use this on a pure android project but whenever I try to implementation it I get:
`Failed to resolve: org.jetbrains.compose.ui:ui:1.2.0-alpha01-dev753`
`Failed to resolve: org.jetbrains.compose.foundation:foundation:1.2.0-alpha01-dev753`
`Failed to resolve: org.jetbrains.compose.runtime:runtime:1.2.0-alpha01-dev753`

I don't believe I'm doing something wrong as I just put the code in like:
`implementation("com.alialbaali.kamel:kamel-image:0.4.1")`

Am I missing something or just having a brain fart?

**Comment by alialbaali** [comment]
Kamel uses builds developed by [JetBrains](https://github.com/JetBrains/compose-jb/releases), which is different from builds used in Jetpack Compose. 

You can try setting up JetBrains Compose using the following [guide](https://github.com/JetBrains/compose-jb/tree/master/tutorials/Getting_Started).
