### ISSUE TITLE
Load images as resources from a jar file

### ISSUE THREAD

**Issue by mipastgt** [alialbaali/Kamel#3]
I'd like to be able to load images as resources from a jar file. This is a very common use case (at least on desktop).

**Comment by alialbaali** [comment]
Have you tried using imageResource or imageFromResource?
Because it seems these methods use the same functionality to load from a jar.

**Comment by mipastgt** [comment]
Yes, that's what I used so far. But having a single API would be nicer.

**Comment by alialbaali** [comment]
Just added support for [that](https://github.com/alialbaali/Kamel/commit/96c52b702f3fc26f83f8279e3feb15d626299b67). It will be available in the next release. You can also check it now using the snapshots repository.

**Comment by mipastgt** [comment]
Thanks, I'll give it a try as soon as the release is out and I get back to Compose.

**Comment by alialbaali** [comment]
Please checkout the new version I just published `0.2.0`. I'm closing this issue.
