### ISSUE TITLE
[Feature Request] Support direct ImageBitmaps instead of only Painters

### ISSUE THREAD

**Issue by Syer10** [alialbaali/Kamel#6]
I was looking into this library to replace my custom KtorImage composable I use around my app. But one thing I noticed is that there isn't a way to pass a FilterQuality parameter like I would use with my ImageBitmaps to allow for cleaner display(not grainy). I played around with using a custom set of composables with your Resource class, but it seems only Painters are supported for loading, the ImageBitmap version is deprecated. So I cant pass a FilterQuality parameter to a Image composable because FilterQuality is only supported for ImageBitmaps.

**Comment by alialbaali** [comment]
Would you like to load images as `ImageBitmap` or have `KamelImage` composable takes an `ImageBitmap` ?

**Comment by Syer10** [comment]
Load images as a ImageBitmap. The backend server provides the images, but they look grainy on low resolutions if I dont use the FilterQuality paramater.

**Comment by alialbaali** [comment]
In version `0.3.0`, `lazyPainterResource` function has `filterQualtiy` parameter.
