### ISSUE TITLE
[Feature Request] Progress float in Resource.Loading

### ISSUE THREAD

**Issue by Syer10** [alialbaali/Kamel#7]
With Ktor 1.6.0, it now allows callbacks with the download progress. For example I do this in my KtorImage composable
```kotlin
    val image = client.get<ByteReadChannel>(url) {
        onDownload { bytesSentTotal, contentLength ->
            progress.value = (bytesSentTotal.toFloat() / contentLength).coerceAtMost(1.0F)
        }
    }.toByteArray()
```
It allows me to set a CircularProgressIndicator with the progress as the real download progress.

**Comment by alialbaali** [comment]
So far I have come to two solutions.

1. One is to have a function just like `onDownload` but in `ResourceConfigBuilder` like this
```kotlin    
val imageResource = lazyPainterResource(generateRandomImageUrl(1)) {
        onLoading { bytesSentTotal, contentLength ->
            progress.value = (bytesSentTotal.toFloat() / contentLength).coerceAtMost(1.0F)
        }
    }

KamelImage(imageResource, null)
```
However in this solution there are gonna be two onLoading callbacks, one in `KamelImage` and one in `lazyPainterResource` which is not the best way to do it to be honest.

2. Returning `Flow` from `fetch` function in `Fetcher` like this
```kotlin
    override suspend fun fetch(data: Url, resourceConfig: ResourceConfig): Flow<Resource> = flow {
        val bytes = client.request<ByteReadChannel> {
            onDownload { bytesSentTotal, contentLength ->
                emit(Resource.Loading((bytesSentTotal.toFloat() / contentLength).coerceAtMost(1.0F)))
            }
            ...
        }
        emit(Resource.Success(bytes))
    }
```
In this method, it would require changing the `Fetcher` API.

What are your thoughts? Do you have a better way to do it?

**Comment by Syer10** [comment]
I think the second way would work pretty well. I agree that the first one is not optimal, as it would require a external progress value for the progress composables to use. The second way would be in my opinion the best way since it would allow the API to be much cleaner in regards to progress, and it would fit very well with the current API(even if it changes the API a bit).

**Comment by alialbaali** [comment]
Please check version `0.3.0` and let me know.
