### ISSUE TITLE
Fail to set image on desktop app with 1.0.0-alpha4-build361

### ISSUE THREAD

**Issue by cmota** [alialbaali/Kamel#8]
Hello!

First, let me say that this is a great lib 🙂 . It really eases handling images on different platforms.

I've just noticed that with the latest version of compose (JetBrains), it's not possible to use Kamel Image on desktop apps:

`Reason=java.lang.NoClassDefFoundError: org/jetbrains/skija/Image`

**Comment by alialbaali** [comment]
Kamel latest version uses `1.0.0-alpha2` of Compose. You'd have to wait for the next release for `alpha4` support

**Comment by alialbaali** [comment]
`0.3.0` version is out with Compose beta1 support.
